from pathlib import Path

import pandas as pd


# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------

# Gold file generated by the durability scoring pipeline
DURABILITY_FILE = Path(
    "data/gold/gold_recipe_durability_scores.parquet"
)


# ------------------------------------------------------------------
# File validation
# ------------------------------------------------------------------

def test_durability_file_exists():
    """
    Ensure that the Gold durability file has been generated.
    """
    assert DURABILITY_FILE.exists()


# ------------------------------------------------------------------
# Schema validation
# ------------------------------------------------------------------

def test_required_columns_exist():
    """
    Ensure that all expected durability columns are present.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    expected_columns = {
        "recipeid",
        "name",
        "seasonality_score",
        "availability_score",
        "durability_score",
        "coverage_score",
    }

    assert expected_columns.issubset(set(df.columns))


def test_no_null_recipeid():
    """
    Every recipe must have a valid identifier.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["recipeid"].notna().all()


# ------------------------------------------------------------------
# Score validation
# ------------------------------------------------------------------

def test_durability_score_between_0_and_100():
    """
    Durability score must be normalized between 0 and 100.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["durability_score"].between(0, 100).all()


def test_seasonality_score_between_0_and_100():
    """
    Seasonality score must be normalized between 0 and 100.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["seasonality_score"].between(0, 100).all()


def test_availability_score_between_0_and_100():
    """
    Agricultural availability score must be normalized between 0 and 100.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["availability_score"].between(0, 100).all()


def test_coverage_score_between_0_and_100():
    """
    Coverage score must be normalized between 0 and 100.
    Coverage represents the percentage of recipe ingredients
    successfully matched to EUFIC and/or FAOSTAT references.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["coverage_score"].between(0, 100).all()

def test_durability_score_not_null():
    """
    Durability score should be computed for every recipe.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["durability_score"].notna().all()


# ------------------------------------------------------------------
# Business validation
# ------------------------------------------------------------------

def test_some_recipes_have_positive_durability_score():
    """
    At least some recipes should receive a positive durability score.
    This validates that the scoring pipeline is not producing only zeros.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert (df["durability_score"] > 0).sum() > 0


def test_coverage_not_empty():
    """
    At least some recipes should have matched ingredients.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert (df["coverage_score"] > 0).sum() > 0


def test_some_recipes_have_seasonality():
    """
    At least some recipes should contain seasonal ingredients.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert (df["seasonality_score"] > 0).sum() > 0


def test_some_recipes_have_availability():
    """
    At least some recipes should contain ingredients available
    in the agricultural production data.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert (df["availability_score"] > 0).sum() > 0


def test_recipeid_unique():
    """
    Final Gold durability dataset should contain one row per recipe.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    assert df["recipeid"].nunique() == len(df)


def test_durability_score_distribution():
    """
    Recipes with the best durability scores should have a higher average
    score than recipes with the lowest durability scores.
    """
    df = pd.read_parquet(DURABILITY_FILE)

    top_100 = df.nlargest(100, "durability_score")
    bottom_100 = df.nsmallest(100, "durability_score")

    assert top_100["durability_score"].mean() > bottom_100["durability_score"].mean()
